version: "3.9"
services:
  db:
    build: ./db
    container_name: db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    environment:
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: postgres
    ports:
      - 10080:10080
volumes:
  postgres: