version: "3.9"
services:
  db:
    build: ./db
    container_name: db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    environment:
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: postgres
    ports:
      - 10080:10080

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: web
    ports:
      - 10070:10070
    environment:
      PORT: 10070

  e2e:
    build:
      context: ./e2e
      dockerfile: Dockerfile
    container_name: e2e
    ports:
      - 10060:10060

  openapi:
    image: redocly/redoc
    container_name: openapi
    volumes:
      - ./api:/usr/share/nginx/html/api
    ports:
      - 10090:10090
volumes:
  postgres: