version: "3.9"
services:
  db:
    build: ./db
    container_name: db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    volumes:
      - ./api:/api
      - ./openapi:/api/openapi
    tty: true
    environment:
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: postgres
    ports:
      - 10080:10080

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: web
    ports:
      - 10070:10070
    environment:
      PORT: 10070
    volumes:
      - type: bind
        source: ./web
        target: /web

  e2e:
    build:
      context: ./e2e
      dockerfile: Dockerfile
    container_name: e2e
    volumes:
      - ./e2e:/app
    working_dir: /app
    ports:
      - 10060:10060

  openapi:
    image: redocly/redoc
    container_name: openapi
    volumes:
      - ./openapi/spec/rest.yaml:/usr/share/nginx/html/openapi/spec/rest.yaml
    environment:
      - SPEC_URL=/openapi/spec/rest.yaml
    ports:
      - 10090:80
volumes:
  postgres: