import type { Metadata } from 'next';
import Header from '@/layouts/Header';
import { Box } from '@mui/material';
import '../styles/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="jp">
      <body style={{ margin: 0 }}>
        <Header />
        <Box bgcolor="grey.100" height={"100vh"}>
        {children}
        </Box>
      </body>
    </html>
  );
}
