import type { Metadata } from "next";
import Header from "@/layouts/Header";
import "../styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="jp">
      <body className="bg-white">
        <Header />
        {children}
      </body>
    </html>
  );
}
