// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CharactersGet implements GET /characters operation.
//
// Get a list of characters.
//
// GET /characters
func (UnimplementedHandler) CharactersGet(ctx context.Context) (r *CharactersGetOK, _ error) {
	return r, ht.ErrNotImplemented
}

// SystemPingGet implements GET /system/ping operation.
//
// System ping.
//
// GET /system/ping
func (UnimplementedHandler) SystemPingGet(ctx context.Context) (r SystemPingGetOK, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrRespStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrRespStatusCode) {
	r = new(ErrRespStatusCode)
	return r
}
