name: "CI api"

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - ".github/workflows/ci-api.yaml"
      - "api/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: "read"

jobs:
  ci-api:
    name: lint

    timeout-minutes: 10

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version-file: "api/go.mod"

      - uses: Jerome1337/gofmt-action@v1.0.5
        with:
          gofmt-path: "./api"
