name: "CI E2E Tests"

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - ".github/workflows/ci-e2e.yaml"
      - "e2e/**"

permissions:
  contents: "read"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-maven-test:
    name: maven-test

    timeout-minutes: 10

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: e2e

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Setup Java
      #   uses: actions/setup-java@v4
      #   with:
      #     distribution: 'adopt'
      #     java-version: '11'

      # - name: Install Gauge
      #   run: curl -SsL https://downloads.gauge.org/stable | sh

      # - name: Install Gauge Java Plugin
      #   run: gauge install java

      # - name: Echo Gauge Version
      #   run: gauge version

      # - name: Run Maven Test
      #   run: mvn test