# yaml-language-server: $schema=https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/schemas/v3.1/schema.json

openapi: '3.1.0'
info:
  title: REST API
  version: 1.0.0
  description: REST API
  contact:
    name: kamegoro
tags:
  - name: ping
paths:
  /system/ping:
    get:
      tags:
        - ping
      summary: system ping
      responses:
        '200':
          description: successful response
          content:
            text/plain:
              schema:
                type: string
                example: pong
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: An unexpected error occurred