# yaml-language-server: $schema=https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/schemas/v3.1/schema.json

openapi: '3.1.0'
info:
  title: REST API
  version: 1.0.0
  description: REST API
  contact:
    name: kamegoro
tags:
  - name: ping
paths:
  /system/ping:
    get:
      tags:
        - ping
      summary: system ping
      responses:
        '200':
          description: successful response
          content:
            text/plain:
              schema:
                type: string
                example: pong
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: An unexpected error occurred
  /characters:
    get:
      summary: Get a list of characters
      responses:
        '200':
          description: A list of characters
          content:
            application/json:
              schema:
                type: object
                required:
                  - characters
                properties:
                  characters:
                    type: array
                    items:
                      type: object
                      required:
                        - id
                        - name
                        - profile
                      properties:
                        id:
                          type: string
                          format: uuid
                          example: "123e4567-e89b-12d3-a456-426614174000"
                        name:
                          type: string
                          example: "John Doe"
                        profile:
                          type: string
                          example: "A brief profile of John Doe."
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: An unexpected error occurred